# Generated by Django 4.0.2 on 2022-03-01 01:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Country',
            fields=[
                ('cid', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=50, verbose_name='Country Name')),
            ],
        ),
        migrations.CreateModel(
            name='AddressFormat',
            fields=[
                ('afid', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100, verbose_name='Formats')),
                ('cid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='address_search.country')),
            ],
        ),
        migrations.CreateModel(
            name='Address',
            fields=[
                ('aid', models.AutoField(primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=10, verbose_name='Title')),
                ('addressee_name', models.CharField(max_length=100, verbose_name='Addressee Name')),
                ('postal_code', models.CharField(max_length=100, verbose_name='Postal Code')),
                ('city', models.CharField(max_length=100, verbose_name='City')),
                ('house_number', models.CharField(max_length=100, verbose_name='House Number')),
                ('building_name', models.CharField(max_length=100, verbose_name='Building Name')),
                ('street_number', models.CharField(max_length=100, verbose_name='Street Number')),
                ('street_name', models.CharField(max_length=100, verbose_name='Street Name')),
                ('postal_symbol', models.CharField(max_length=100, verbose_name='Postal Symbol')),
                ('company_name', models.CharField(max_length=100, verbose_name='Company Name')),
                ('cid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='address_search.country')),
            ],
        ),
    ]
