# Generated by Django 4.0.2 on 2022-02-08 19:43

from django.db import migrations, models
import imageupload.models


class Migration(migrations.Migration):

    dependencies = [
        ('imageupload', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='uploadimage',
            name='image',
            field=models.ImageField(upload_to=imageupload.models.scramble_upload_filename, verbose_name='Upload Image'),
        ),
    ]
